name: 'portainer stack deploy'
description: 'Github Action for portainer, continuous deploy image to portainer by remote endpoint'
author: 'LGinC <liguo1976@outlook.com>'
branding: 
 icon: 'portainer'
 color: 'blue'
inputs:
  serverurl:
    description: 'portainer server url'
    required: true
  username:
    description: 'portainer admin user name'
    required: true
  password:
    description: 'portainer admin user password'
    required: true
  endpointId:
    description: 'portainer EndpointId,default 1'
    required: false
    default: 1
  stackname:
    description: 'name of stack, lowercase'
    required: true
  imagename:
    description: 'deploy image name'
    required: true
  docker_compose:
    description: 'content of docker-compose.yml, just support version 2'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
