name: CI
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target=${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: portainer-deploy-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/portainer-deploy
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: download amd64 binary
        uses: actions/download-artifact@v2
        with:
          name: portainer-deploy-x86_64-unknown-linux-musl
          path: docker/
      - run: cd docker && mv portainer-deploy portainer-deploy-amd64
      - name: download arm64 binary
        uses: actions/download-artifact@v2
        with:
          name: portainer-deploy-aarch64-unknown-linux-musl
          path: docker/
      - run: cd docker && mv portainer-deploy portainer-deploy-arm64
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest