name: MyAction

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: LGinC/portainer-stack-deploy@master
      with:
        serverurl: http://1065.cloud:8862
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_USERNAME }}
        endpointId: 2
        stackname: destinyApi
        docker_compose: |
          version: "2"
          services:
            destinyapi:
              image: registry.cn-shanghai.aliyuncs.com/destinycore/destinyflowapi
              container_name: DestinyFlowAPI
              ports:
              - 5000:80
